//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ALPA.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities_Korber : DbContext
    {
        public Entities_Korber()
            : base("name=Entities_Korber")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int DRIVIN_Eliminar_direcciones(ObjectParameter rpta)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRIVIN_Eliminar_direcciones", rpta);
        }
    
        public virtual ObjectResult<DRIVIN_Listar_Clientes_Result> DRIVIN_Listar_Clientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DRIVIN_Listar_Clientes_Result>("DRIVIN_Listar_Clientes");
        }
    
        public virtual int DRIVIN_Insertar_esquema(string code, string name, ObjectParameter rpta)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRIVIN_Insertar_esquema", codeParameter, nameParameter, rpta);
        }
    
        public virtual ObjectResult<DRIVIN_Listar_Direcciones_Result> DRIVIN_Listar_Direcciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DRIVIN_Listar_Direcciones_Result>("DRIVIN_Listar_Direcciones");
        }
    
        public virtual int DRIVIN_Insertar_direccion(string code, string name, string client, string address_type, string address1, string address2, string city, string state, string country, string lat, string lng, Nullable<bool> georeferenced, ObjectParameter rpta)
        {
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var clientParameter = client != null ?
                new ObjectParameter("client", client) :
                new ObjectParameter("client", typeof(string));
    
            var address_typeParameter = address_type != null ?
                new ObjectParameter("address_type", address_type) :
                new ObjectParameter("address_type", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("address1", address1) :
                new ObjectParameter("address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("address2", address2) :
                new ObjectParameter("address2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var latParameter = lat != null ?
                new ObjectParameter("lat", lat) :
                new ObjectParameter("lat", typeof(string));
    
            var lngParameter = lng != null ?
                new ObjectParameter("lng", lng) :
                new ObjectParameter("lng", typeof(string));
    
            var georeferencedParameter = georeferenced.HasValue ?
                new ObjectParameter("georeferenced", georeferenced) :
                new ObjectParameter("georeferenced", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRIVIN_Insertar_direccion", codeParameter, nameParameter, clientParameter, address_typeParameter, address1Parameter, address2Parameter, cityParameter, stateParameter, countryParameter, latParameter, lngParameter, georeferencedParameter, rpta);
        }
    
        public virtual int DRIVIN_SAP_Update_Estado(string orderNumber, string numeroGuia, string custPoNumber, string referencia, string tokenEscenario, ObjectParameter rpta)
        {
            var orderNumberParameter = orderNumber != null ?
                new ObjectParameter("OrderNumber", orderNumber) :
                new ObjectParameter("OrderNumber", typeof(string));
    
            var numeroGuiaParameter = numeroGuia != null ?
                new ObjectParameter("NumeroGuia", numeroGuia) :
                new ObjectParameter("NumeroGuia", typeof(string));
    
            var custPoNumberParameter = custPoNumber != null ?
                new ObjectParameter("CustPoNumber", custPoNumber) :
                new ObjectParameter("CustPoNumber", typeof(string));
    
            var referenciaParameter = referencia != null ?
                new ObjectParameter("Referencia", referencia) :
                new ObjectParameter("Referencia", typeof(string));
    
            var tokenEscenarioParameter = tokenEscenario != null ?
                new ObjectParameter("TokenEscenario", tokenEscenario) :
                new ObjectParameter("TokenEscenario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRIVIN_SAP_Update_Estado", orderNumberParameter, numeroGuiaParameter, custPoNumberParameter, referenciaParameter, tokenEscenarioParameter, rpta);
        }
    
        public virtual int DRIVIN_SAP_update_Pedidos(string pedido, string numeroGuia, string referencia, string whId, string placa, string tiempoServicio, string inicioVentana, string finVentana, string fechaDespacho, string convoy, ObjectParameter rpta)
        {
            var pedidoParameter = pedido != null ?
                new ObjectParameter("Pedido", pedido) :
                new ObjectParameter("Pedido", typeof(string));
    
            var numeroGuiaParameter = numeroGuia != null ?
                new ObjectParameter("NumeroGuia", numeroGuia) :
                new ObjectParameter("NumeroGuia", typeof(string));
    
            var referenciaParameter = referencia != null ?
                new ObjectParameter("Referencia", referencia) :
                new ObjectParameter("Referencia", typeof(string));
    
            var whIdParameter = whId != null ?
                new ObjectParameter("WhId", whId) :
                new ObjectParameter("WhId", typeof(string));
    
            var placaParameter = placa != null ?
                new ObjectParameter("Placa", placa) :
                new ObjectParameter("Placa", typeof(string));
    
            var tiempoServicioParameter = tiempoServicio != null ?
                new ObjectParameter("TiempoServicio", tiempoServicio) :
                new ObjectParameter("TiempoServicio", typeof(string));
    
            var inicioVentanaParameter = inicioVentana != null ?
                new ObjectParameter("InicioVentana", inicioVentana) :
                new ObjectParameter("InicioVentana", typeof(string));
    
            var finVentanaParameter = finVentana != null ?
                new ObjectParameter("FinVentana", finVentana) :
                new ObjectParameter("FinVentana", typeof(string));
    
            var fechaDespachoParameter = fechaDespacho != null ?
                new ObjectParameter("FechaDespacho", fechaDespacho) :
                new ObjectParameter("FechaDespacho", typeof(string));
    
            var convoyParameter = convoy != null ?
                new ObjectParameter("Convoy", convoy) :
                new ObjectParameter("Convoy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRIVIN_SAP_update_Pedidos", pedidoParameter, numeroGuiaParameter, referenciaParameter, whIdParameter, placaParameter, tiempoServicioParameter, inicioVentanaParameter, finVentanaParameter, fechaDespachoParameter, convoyParameter, rpta);
        }
    
        public virtual int DRIVIN_Insertar_transportista(string email, string phone, string first_name, string last_name, string dni, string license_number, string role_name, string organization, ObjectParameter rpta)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var license_numberParameter = license_number != null ?
                new ObjectParameter("license_number", license_number) :
                new ObjectParameter("license_number", typeof(string));
    
            var role_nameParameter = role_name != null ?
                new ObjectParameter("role_name", role_name) :
                new ObjectParameter("role_name", typeof(string));
    
            var organizationParameter = organization != null ?
                new ObjectParameter("organization", organization) :
                new ObjectParameter("organization", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRIVIN_Insertar_transportista", emailParameter, phoneParameter, first_nameParameter, last_nameParameter, dniParameter, license_numberParameter, role_nameParameter, organizationParameter, rpta);
        }
    
        public virtual int DRIVIN_SAP_Update_Placa_Guia(string numeroGuia, string placaIndividual, Nullable<int> prioridad, string licencia, string custPoNumber, ObjectParameter rpta)
        {
            var numeroGuiaParameter = numeroGuia != null ?
                new ObjectParameter("NumeroGuia", numeroGuia) :
                new ObjectParameter("NumeroGuia", typeof(string));
    
            var placaIndividualParameter = placaIndividual != null ?
                new ObjectParameter("PlacaIndividual", placaIndividual) :
                new ObjectParameter("PlacaIndividual", typeof(string));
    
            var prioridadParameter = prioridad.HasValue ?
                new ObjectParameter("Prioridad", prioridad) :
                new ObjectParameter("Prioridad", typeof(int));
    
            var licenciaParameter = licencia != null ?
                new ObjectParameter("Licencia", licencia) :
                new ObjectParameter("Licencia", typeof(string));
    
            var custPoNumberParameter = custPoNumber != null ?
                new ObjectParameter("CustPoNumber", custPoNumber) :
                new ObjectParameter("CustPoNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRIVIN_SAP_Update_Placa_Guia", numeroGuiaParameter, placaIndividualParameter, prioridadParameter, licenciaParameter, custPoNumberParameter, rpta);
        }
    
        public virtual int DRIVIN_Eliminar_escenarios(ObjectParameter rpta)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRIVIN_Eliminar_escenarios", rpta);
        }
    
        public virtual int DRIVIN_Insertar_escenarios(string token, string description, string status, string schema_name, string schema_code, ObjectParameter rpta)
        {
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var schema_nameParameter = schema_name != null ?
                new ObjectParameter("schema_name", schema_name) :
                new ObjectParameter("schema_name", typeof(string));
    
            var schema_codeParameter = schema_code != null ?
                new ObjectParameter("schema_code", schema_code) :
                new ObjectParameter("schema_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRIVIN_Insertar_escenarios", tokenParameter, descriptionParameter, statusParameter, schema_nameParameter, schema_codeParameter, rpta);
        }
    
        public virtual int DRIVIN_execute_job()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRIVIN_execute_job");
        }
    
        public virtual ObjectResult<DRIVIN_SAP_Listar_Pedidos_Result> DRIVIN_SAP_Listar_Pedidos(string fechaIni, string fechaFin, string clientId, string whId, string orderNumber, Nullable<int> estadoDrivin, string formaEnvioDrivin, string busquedaGeneral, string lineaNegocio, string placaGeneral)
        {
            var fechaIniParameter = fechaIni != null ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(string));
    
            var clientIdParameter = clientId != null ?
                new ObjectParameter("ClientId", clientId) :
                new ObjectParameter("ClientId", typeof(string));
    
            var whIdParameter = whId != null ?
                new ObjectParameter("WhId", whId) :
                new ObjectParameter("WhId", typeof(string));
    
            var orderNumberParameter = orderNumber != null ?
                new ObjectParameter("OrderNumber", orderNumber) :
                new ObjectParameter("OrderNumber", typeof(string));
    
            var estadoDrivinParameter = estadoDrivin.HasValue ?
                new ObjectParameter("EstadoDrivin", estadoDrivin) :
                new ObjectParameter("EstadoDrivin", typeof(int));
    
            var formaEnvioDrivinParameter = formaEnvioDrivin != null ?
                new ObjectParameter("FormaEnvioDrivin", formaEnvioDrivin) :
                new ObjectParameter("FormaEnvioDrivin", typeof(string));
    
            var busquedaGeneralParameter = busquedaGeneral != null ?
                new ObjectParameter("BusquedaGeneral", busquedaGeneral) :
                new ObjectParameter("BusquedaGeneral", typeof(string));
    
            var lineaNegocioParameter = lineaNegocio != null ?
                new ObjectParameter("LineaNegocio", lineaNegocio) :
                new ObjectParameter("LineaNegocio", typeof(string));
    
            var placaGeneralParameter = placaGeneral != null ?
                new ObjectParameter("PlacaGeneral", placaGeneral) :
                new ObjectParameter("PlacaGeneral", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DRIVIN_SAP_Listar_Pedidos_Result>("DRIVIN_SAP_Listar_Pedidos", fechaIniParameter, fechaFinParameter, clientIdParameter, whIdParameter, orderNumberParameter, estadoDrivinParameter, formaEnvioDrivinParameter, busquedaGeneralParameter, lineaNegocioParameter, placaGeneralParameter);
        }
    
        public virtual int DRIVIN_Insertar_vehiculo(string id, string code, string description, Nullable<double> capacity_1, Nullable<double> capacity_2, Nullable<double> capacity_3, string flotas, ObjectParameter rpta)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var capacity_1Parameter = capacity_1.HasValue ?
                new ObjectParameter("capacity_1", capacity_1) :
                new ObjectParameter("capacity_1", typeof(double));
    
            var capacity_2Parameter = capacity_2.HasValue ?
                new ObjectParameter("capacity_2", capacity_2) :
                new ObjectParameter("capacity_2", typeof(double));
    
            var capacity_3Parameter = capacity_3.HasValue ?
                new ObjectParameter("capacity_3", capacity_3) :
                new ObjectParameter("capacity_3", typeof(double));
    
            var flotasParameter = flotas != null ?
                new ObjectParameter("flotas", flotas) :
                new ObjectParameter("flotas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRIVIN_Insertar_vehiculo", idParameter, codeParameter, descriptionParameter, capacity_1Parameter, capacity_2Parameter, capacity_3Parameter, flotasParameter, rpta);
        }
    
        public virtual int DRIVIN_Insertar_licencias_securitas(string id_licencia, string name, string description, ObjectParameter rpta)
        {
            var id_licenciaParameter = id_licencia != null ?
                new ObjectParameter("id_licencia", id_licencia) :
                new ObjectParameter("id_licencia", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRIVIN_Insertar_licencias_securitas", id_licenciaParameter, nameParameter, descriptionParameter, rpta);
        }
    
        public virtual int DRIVIN_Insertar_placa_securitas(string placa, string tipo, string name, string identificador, ObjectParameter rpta)
        {
            var placaParameter = placa != null ?
                new ObjectParameter("placa", placa) :
                new ObjectParameter("placa", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var identificadorParameter = identificador != null ?
                new ObjectParameter("identificador", identificador) :
                new ObjectParameter("identificador", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DRIVIN_Insertar_placa_securitas", placaParameter, tipoParameter, nameParameter, identificadorParameter, rpta);
        }
    
        public virtual ObjectResult<KORBER_Listar_OrdenCompra_Det_Result> KORBER_Listar_OrdenCompra_Det(string ordenCompra)
        {
            var ordenCompraParameter = ordenCompra != null ?
                new ObjectParameter("OrdenCompra", ordenCompra) :
                new ObjectParameter("OrdenCompra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KORBER_Listar_OrdenCompra_Det_Result>("KORBER_Listar_OrdenCompra_Det", ordenCompraParameter);
        }
    
        public virtual ObjectResult<DRIVIN_Listar_General_Result> DRIVIN_Listar_General(string sTabla)
        {
            var sTablaParameter = sTabla != null ?
                new ObjectParameter("sTabla", sTabla) :
                new ObjectParameter("sTabla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DRIVIN_Listar_General_Result>("DRIVIN_Listar_General", sTablaParameter);
        }
    
        public virtual ObjectResult<DRIVIN_Listar_General_Conductor_Result> DRIVIN_Listar_General_Conductor(string sTabla)
        {
            var sTablaParameter = sTabla != null ?
                new ObjectParameter("sTabla", sTabla) :
                new ObjectParameter("sTabla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DRIVIN_Listar_General_Conductor_Result>("DRIVIN_Listar_General_Conductor", sTablaParameter);
        }
    
        public virtual ObjectResult<KORBER_Listar_OrdenCompra_Cab_Result> KORBER_Listar_OrdenCompra_Cab(string ordenCompra)
        {
            var ordenCompraParameter = ordenCompra != null ?
                new ObjectParameter("OrdenCompra", ordenCompra) :
                new ObjectParameter("OrdenCompra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KORBER_Listar_OrdenCompra_Cab_Result>("KORBER_Listar_OrdenCompra_Cab", ordenCompraParameter);
        }
    
        public virtual int KORBER_SP_INFORME_MERCADERIA_CAB_INS(string wh_id, string client_code, string nro_orden_compra, string codigo_negocio, string conductor, string nro_dni, string nro_licencia, Nullable<int> id_tipo_vehiculo, Nullable<int> id_tipo_compra, Nullable<int> id_tipo_carga, string nro_placa, string nro_contenedor, string nro_precinto, string nro_soat, string nro_dua, string nro_traslado, string nro_bill_lading, string nro_factura, string nro_guia_remision, Nullable<System.DateTime> fecha_recepcion, Nullable<System.DateTime> fecha_registro, Nullable<System.DateTime> fecha_informe, ObjectParameter rpta)
        {
            var wh_idParameter = wh_id != null ?
                new ObjectParameter("wh_id", wh_id) :
                new ObjectParameter("wh_id", typeof(string));
    
            var client_codeParameter = client_code != null ?
                new ObjectParameter("client_code", client_code) :
                new ObjectParameter("client_code", typeof(string));
    
            var nro_orden_compraParameter = nro_orden_compra != null ?
                new ObjectParameter("nro_orden_compra", nro_orden_compra) :
                new ObjectParameter("nro_orden_compra", typeof(string));
    
            var codigo_negocioParameter = codigo_negocio != null ?
                new ObjectParameter("codigo_negocio", codigo_negocio) :
                new ObjectParameter("codigo_negocio", typeof(string));
    
            var conductorParameter = conductor != null ?
                new ObjectParameter("conductor", conductor) :
                new ObjectParameter("conductor", typeof(string));
    
            var nro_dniParameter = nro_dni != null ?
                new ObjectParameter("nro_dni", nro_dni) :
                new ObjectParameter("nro_dni", typeof(string));
    
            var nro_licenciaParameter = nro_licencia != null ?
                new ObjectParameter("nro_licencia", nro_licencia) :
                new ObjectParameter("nro_licencia", typeof(string));
    
            var id_tipo_vehiculoParameter = id_tipo_vehiculo.HasValue ?
                new ObjectParameter("id_tipo_vehiculo", id_tipo_vehiculo) :
                new ObjectParameter("id_tipo_vehiculo", typeof(int));
    
            var id_tipo_compraParameter = id_tipo_compra.HasValue ?
                new ObjectParameter("id_tipo_compra", id_tipo_compra) :
                new ObjectParameter("id_tipo_compra", typeof(int));
    
            var id_tipo_cargaParameter = id_tipo_carga.HasValue ?
                new ObjectParameter("id_tipo_carga", id_tipo_carga) :
                new ObjectParameter("id_tipo_carga", typeof(int));
    
            var nro_placaParameter = nro_placa != null ?
                new ObjectParameter("nro_placa", nro_placa) :
                new ObjectParameter("nro_placa", typeof(string));
    
            var nro_contenedorParameter = nro_contenedor != null ?
                new ObjectParameter("nro_contenedor", nro_contenedor) :
                new ObjectParameter("nro_contenedor", typeof(string));
    
            var nro_precintoParameter = nro_precinto != null ?
                new ObjectParameter("nro_precinto", nro_precinto) :
                new ObjectParameter("nro_precinto", typeof(string));
    
            var nro_soatParameter = nro_soat != null ?
                new ObjectParameter("nro_soat", nro_soat) :
                new ObjectParameter("nro_soat", typeof(string));
    
            var nro_duaParameter = nro_dua != null ?
                new ObjectParameter("nro_dua", nro_dua) :
                new ObjectParameter("nro_dua", typeof(string));
    
            var nro_trasladoParameter = nro_traslado != null ?
                new ObjectParameter("nro_traslado", nro_traslado) :
                new ObjectParameter("nro_traslado", typeof(string));
    
            var nro_bill_ladingParameter = nro_bill_lading != null ?
                new ObjectParameter("nro_bill_lading", nro_bill_lading) :
                new ObjectParameter("nro_bill_lading", typeof(string));
    
            var nro_facturaParameter = nro_factura != null ?
                new ObjectParameter("nro_factura", nro_factura) :
                new ObjectParameter("nro_factura", typeof(string));
    
            var nro_guia_remisionParameter = nro_guia_remision != null ?
                new ObjectParameter("nro_guia_remision", nro_guia_remision) :
                new ObjectParameter("nro_guia_remision", typeof(string));
    
            var fecha_recepcionParameter = fecha_recepcion.HasValue ?
                new ObjectParameter("fecha_recepcion", fecha_recepcion) :
                new ObjectParameter("fecha_recepcion", typeof(System.DateTime));
    
            var fecha_registroParameter = fecha_registro.HasValue ?
                new ObjectParameter("fecha_registro", fecha_registro) :
                new ObjectParameter("fecha_registro", typeof(System.DateTime));
    
            var fecha_informeParameter = fecha_informe.HasValue ?
                new ObjectParameter("fecha_informe", fecha_informe) :
                new ObjectParameter("fecha_informe", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KORBER_SP_INFORME_MERCADERIA_CAB_INS", wh_idParameter, client_codeParameter, nro_orden_compraParameter, codigo_negocioParameter, conductorParameter, nro_dniParameter, nro_licenciaParameter, id_tipo_vehiculoParameter, id_tipo_compraParameter, id_tipo_cargaParameter, nro_placaParameter, nro_contenedorParameter, nro_precintoParameter, nro_soatParameter, nro_duaParameter, nro_trasladoParameter, nro_bill_ladingParameter, nro_facturaParameter, nro_guia_remisionParameter, fecha_recepcionParameter, fecha_registroParameter, fecha_informeParameter, rpta);
        }
    
        public virtual int KOBER_SP_INFORME_DET_OBSERVADOS(Nullable<int> id_observado, Nullable<int> id_detalle, string comentario, string conclusiones, ObjectParameter rpta)
        {
            var id_observadoParameter = id_observado.HasValue ?
                new ObjectParameter("id_observado", id_observado) :
                new ObjectParameter("id_observado", typeof(int));
    
            var id_detalleParameter = id_detalle.HasValue ?
                new ObjectParameter("id_detalle", id_detalle) :
                new ObjectParameter("id_detalle", typeof(int));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("comentario", comentario) :
                new ObjectParameter("comentario", typeof(string));
    
            var conclusionesParameter = conclusiones != null ?
                new ObjectParameter("conclusiones", conclusiones) :
                new ObjectParameter("conclusiones", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KOBER_SP_INFORME_DET_OBSERVADOS", id_observadoParameter, id_detalleParameter, comentarioParameter, conclusionesParameter, rpta);
        }
    
        public virtual ObjectResult<KORBER_Listar_OrdenCompra_OBS_Result> KORBER_Listar_OrdenCompra_OBS(Nullable<int> id_detalle)
        {
            var id_detalleParameter = id_detalle.HasValue ?
                new ObjectParameter("id_detalle", id_detalle) :
                new ObjectParameter("id_detalle", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KORBER_Listar_OrdenCompra_OBS_Result>("KORBER_Listar_OrdenCompra_OBS", id_detalleParameter);
        }
    
        public virtual int KOBER_SP_INFORME_DET_IMAGENES(Nullable<int> id_imagen, string nro_orden_compra, string nombre, string descripcion, byte[] imagen, ObjectParameter rpta)
        {
            var id_imagenParameter = id_imagen.HasValue ?
                new ObjectParameter("id_imagen", id_imagen) :
                new ObjectParameter("id_imagen", typeof(int));
    
            var nro_orden_compraParameter = nro_orden_compra != null ?
                new ObjectParameter("nro_orden_compra", nro_orden_compra) :
                new ObjectParameter("nro_orden_compra", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KOBER_SP_INFORME_DET_IMAGENES", id_imagenParameter, nro_orden_compraParameter, nombreParameter, descripcionParameter, imagenParameter, rpta);
        }
    
        public virtual ObjectResult<KORBER_Listar_OrdenCompra_IMG_Result> KORBER_Listar_OrdenCompra_IMG(string nro_orden_compra)
        {
            var nro_orden_compraParameter = nro_orden_compra != null ?
                new ObjectParameter("nro_orden_compra", nro_orden_compra) :
                new ObjectParameter("nro_orden_compra", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KORBER_Listar_OrdenCompra_IMG_Result>("KORBER_Listar_OrdenCompra_IMG", nro_orden_compraParameter);
        }
    }
}
