//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ALPA.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ALPA_WEBEntities : DbContext
    {
        public ALPA_WEBEntities()
            : base("name=ALPA_WEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<USP_Listar_Menu_Result> GET_Listar_Menu(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Listar_Menu_Result>("GET_Listar_Menu", userIDParameter);
        }
    
        public virtual ObjectResult<USP_Listar_MenuPermiso_Result> GET_Listar_MenuPermiso(string userID, string roleID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var roleIDParameter = roleID != null ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Listar_MenuPermiso_Result>("GET_Listar_MenuPermiso", userIDParameter, roleIDParameter);
        }
    
        public virtual ObjectResult<USP_Listar_Roles_Result> GET_Listar_Roles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Listar_Roles_Result>("GET_Listar_Roles");
        }
    
        public virtual int UPDATE_Permisos(Nullable<int> menuID, Nullable<int> userID, Nullable<int> roleID, Nullable<int> permisoType, Nullable<int> permiso, ObjectParameter rpta)
        {
            var menuIDParameter = menuID.HasValue ?
                new ObjectParameter("MenuID", menuID) :
                new ObjectParameter("MenuID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var roleIDParameter = roleID.HasValue ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(int));
    
            var permisoTypeParameter = permisoType.HasValue ?
                new ObjectParameter("PermisoType", permisoType) :
                new ObjectParameter("PermisoType", typeof(int));
    
            var permisoParameter = permiso.HasValue ?
                new ObjectParameter("Permiso", permiso) :
                new ObjectParameter("Permiso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_Permisos", menuIDParameter, userIDParameter, roleIDParameter, permisoTypeParameter, permisoParameter, rpta);
        }
    
        public virtual int UPDATE_Usuario_Rol(Nullable<int> userId, Nullable<int> u_RoleId, ObjectParameter rpta)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var u_RoleIdParameter = u_RoleId.HasValue ?
                new ObjectParameter("U_RoleId", u_RoleId) :
                new ObjectParameter("U_RoleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_Usuario_Rol", userIdParameter, u_RoleIdParameter, rpta);
        }
    
        public virtual int POST_ProgInventarioFavo_Cab(string u_FechaProgramacion, string u_UsuarioRegistro, string u_CodAlmacen, string u_Comentario, Nullable<bool> u_ProgParcial, ObjectParameter u_NroDocumento, ObjectParameter rpta)
        {
            var u_FechaProgramacionParameter = u_FechaProgramacion != null ?
                new ObjectParameter("U_FechaProgramacion", u_FechaProgramacion) :
                new ObjectParameter("U_FechaProgramacion", typeof(string));
    
            var u_UsuarioRegistroParameter = u_UsuarioRegistro != null ?
                new ObjectParameter("U_UsuarioRegistro", u_UsuarioRegistro) :
                new ObjectParameter("U_UsuarioRegistro", typeof(string));
    
            var u_CodAlmacenParameter = u_CodAlmacen != null ?
                new ObjectParameter("U_CodAlmacen", u_CodAlmacen) :
                new ObjectParameter("U_CodAlmacen", typeof(string));
    
            var u_ComentarioParameter = u_Comentario != null ?
                new ObjectParameter("U_Comentario", u_Comentario) :
                new ObjectParameter("U_Comentario", typeof(string));
    
            var u_ProgParcialParameter = u_ProgParcial.HasValue ?
                new ObjectParameter("U_ProgParcial", u_ProgParcial) :
                new ObjectParameter("U_ProgParcial", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_ProgInventarioFavo_Cab", u_FechaProgramacionParameter, u_UsuarioRegistroParameter, u_CodAlmacenParameter, u_ComentarioParameter, u_ProgParcialParameter, u_NroDocumento, rpta);
        }
    
        public virtual int POST_ProgInventarioFavo_Locacion(Nullable<int> u_NroDocumento, string u_CodUbicacion, ObjectParameter rpta)
        {
            var u_NroDocumentoParameter = u_NroDocumento.HasValue ?
                new ObjectParameter("U_NroDocumento", u_NroDocumento) :
                new ObjectParameter("U_NroDocumento", typeof(int));
    
            var u_CodUbicacionParameter = u_CodUbicacion != null ?
                new ObjectParameter("U_CodUbicacion", u_CodUbicacion) :
                new ObjectParameter("U_CodUbicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_ProgInventarioFavo_Locacion", u_NroDocumentoParameter, u_CodUbicacionParameter, rpta);
        }
    
        public virtual ObjectResult<USP_Web_Listar_ProgInventarioFavo_Cab_Result> GET_Listar_ProgInventarioFavo_Cab(string u_FecDesde, string u_FecHasta, Nullable<int> u_NroDocumento, Nullable<int> u_Cerrado)
        {
            var u_FecDesdeParameter = u_FecDesde != null ?
                new ObjectParameter("U_FecDesde", u_FecDesde) :
                new ObjectParameter("U_FecDesde", typeof(string));
    
            var u_FecHastaParameter = u_FecHasta != null ?
                new ObjectParameter("U_FecHasta", u_FecHasta) :
                new ObjectParameter("U_FecHasta", typeof(string));
    
            var u_NroDocumentoParameter = u_NroDocumento.HasValue ?
                new ObjectParameter("U_NroDocumento", u_NroDocumento) :
                new ObjectParameter("U_NroDocumento", typeof(int));
    
            var u_CerradoParameter = u_Cerrado.HasValue ?
                new ObjectParameter("U_Cerrado", u_Cerrado) :
                new ObjectParameter("U_Cerrado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_ProgInventarioFavo_Cab_Result>("GET_Listar_ProgInventarioFavo_Cab", u_FecDesdeParameter, u_FecHastaParameter, u_NroDocumentoParameter, u_CerradoParameter);
        }
    
        public virtual ObjectResult<USP_Web_Listar_ProgInventarioFavo_Locacion_Result> GET_Listar_ProgInventarioFavo_Locacion(Nullable<int> u_NroDocumento, string u_CodUbicacion)
        {
            var u_NroDocumentoParameter = u_NroDocumento.HasValue ?
                new ObjectParameter("U_NroDocumento", u_NroDocumento) :
                new ObjectParameter("U_NroDocumento", typeof(int));
    
            var u_CodUbicacionParameter = u_CodUbicacion != null ?
                new ObjectParameter("U_CodUbicacion", u_CodUbicacion) :
                new ObjectParameter("U_CodUbicacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_ProgInventarioFavo_Locacion_Result>("GET_Listar_ProgInventarioFavo_Locacion", u_NroDocumentoParameter, u_CodUbicacionParameter);
        }
    
        public virtual int POST_ProgInventarioFavo_LocacionStock(Nullable<int> u_NroDocumento, string u_CodUbicacion, string u_CodProducto, string u_LoteSerie, Nullable<System.DateTime> u_Producto_FecVcto, Nullable<decimal> u_CantOperacion, string u_UsuarioRegistro, ObjectParameter rpta)
        {
            var u_NroDocumentoParameter = u_NroDocumento.HasValue ?
                new ObjectParameter("U_NroDocumento", u_NroDocumento) :
                new ObjectParameter("U_NroDocumento", typeof(int));
    
            var u_CodUbicacionParameter = u_CodUbicacion != null ?
                new ObjectParameter("U_CodUbicacion", u_CodUbicacion) :
                new ObjectParameter("U_CodUbicacion", typeof(string));
    
            var u_CodProductoParameter = u_CodProducto != null ?
                new ObjectParameter("U_CodProducto", u_CodProducto) :
                new ObjectParameter("U_CodProducto", typeof(string));
    
            var u_LoteSerieParameter = u_LoteSerie != null ?
                new ObjectParameter("U_LoteSerie", u_LoteSerie) :
                new ObjectParameter("U_LoteSerie", typeof(string));
    
            var u_Producto_FecVctoParameter = u_Producto_FecVcto.HasValue ?
                new ObjectParameter("U_Producto_FecVcto", u_Producto_FecVcto) :
                new ObjectParameter("U_Producto_FecVcto", typeof(System.DateTime));
    
            var u_CantOperacionParameter = u_CantOperacion.HasValue ?
                new ObjectParameter("U_CantOperacion", u_CantOperacion) :
                new ObjectParameter("U_CantOperacion", typeof(decimal));
    
            var u_UsuarioRegistroParameter = u_UsuarioRegistro != null ?
                new ObjectParameter("U_UsuarioRegistro", u_UsuarioRegistro) :
                new ObjectParameter("U_UsuarioRegistro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_ProgInventarioFavo_LocacionStock", u_NroDocumentoParameter, u_CodUbicacionParameter, u_CodProductoParameter, u_LoteSerieParameter, u_Producto_FecVctoParameter, u_CantOperacionParameter, u_UsuarioRegistroParameter, rpta);
        }
    
        public virtual ObjectResult<USP_Web_Listar_ProgInventarioFavo_LS_Result> GET_Listar_ProgInventarioFavo_LS(Nullable<int> u_NroDocumento)
        {
            var u_NroDocumentoParameter = u_NroDocumento.HasValue ?
                new ObjectParameter("U_NroDocumento", u_NroDocumento) :
                new ObjectParameter("U_NroDocumento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_ProgInventarioFavo_LS_Result>("GET_Listar_ProgInventarioFavo_LS", u_NroDocumentoParameter);
        }
    
        public virtual ObjectResult<USP_Web_Listar_ProgInventarioFavo_Comparativo_Result> GET_Listar_ProgInventarioFavo_Comparativo(Nullable<int> u_NroDocumento)
        {
            var u_NroDocumentoParameter = u_NroDocumento.HasValue ?
                new ObjectParameter("U_NroDocumento", u_NroDocumento) :
                new ObjectParameter("U_NroDocumento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_ProgInventarioFavo_Comparativo_Result>("GET_Listar_ProgInventarioFavo_Comparativo", u_NroDocumentoParameter);
        }
    
        public virtual ObjectResult<USP_Web_Listar_TipoDocumento_Result> GET_Listar_TipoDocumento(Nullable<int> u_Cod)
        {
            var u_CodParameter = u_Cod.HasValue ?
                new ObjectParameter("U_Cod", u_Cod) :
                new ObjectParameter("U_Cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_TipoDocumento_Result>("GET_Listar_TipoDocumento", u_CodParameter);
        }
    
        public virtual int POST_Personal(Nullable<int> u_TipoDocumento, string u_DocIdentidad, string u_Nombre, string u_Apellidos, string u_CodEmpresa, Nullable<bool> u_Cuestionario, Nullable<System.DateTime> u_FechaCuestionarioInicio, Nullable<System.DateTime> u_FechaCuestionarioFin, Nullable<bool> u_Vacunacion, Nullable<int> u_NroDosis, Nullable<bool> u_SCTR, Nullable<System.DateTime> u_FechaSCTRInicio, Nullable<System.DateTime> u_FechaSCTRFin, Nullable<bool> u_Induccion, Nullable<bool> u_LicenciaConducir, Nullable<System.DateTime> u_FechaLicenciaInicio, Nullable<System.DateTime> u_FechaLicenciaFin, string u_Email, Nullable<bool> u_ListaNegra, string u_MotivoListaNegra, Nullable<System.DateTime> u_FechaListaNegra, Nullable<bool> u_Sancionado, Nullable<System.DateTime> u_FechaSancionInicio, Nullable<System.DateTime> u_FechaSancionFin, string u_UsuarioRegistro, ObjectParameter rpta, ObjectParameter valRpta)
        {
            var u_TipoDocumentoParameter = u_TipoDocumento.HasValue ?
                new ObjectParameter("U_TipoDocumento", u_TipoDocumento) :
                new ObjectParameter("U_TipoDocumento", typeof(int));
    
            var u_DocIdentidadParameter = u_DocIdentidad != null ?
                new ObjectParameter("U_DocIdentidad", u_DocIdentidad) :
                new ObjectParameter("U_DocIdentidad", typeof(string));
    
            var u_NombreParameter = u_Nombre != null ?
                new ObjectParameter("U_Nombre", u_Nombre) :
                new ObjectParameter("U_Nombre", typeof(string));
    
            var u_ApellidosParameter = u_Apellidos != null ?
                new ObjectParameter("U_Apellidos", u_Apellidos) :
                new ObjectParameter("U_Apellidos", typeof(string));
    
            var u_CodEmpresaParameter = u_CodEmpresa != null ?
                new ObjectParameter("U_CodEmpresa", u_CodEmpresa) :
                new ObjectParameter("U_CodEmpresa", typeof(string));
    
            var u_CuestionarioParameter = u_Cuestionario.HasValue ?
                new ObjectParameter("U_Cuestionario", u_Cuestionario) :
                new ObjectParameter("U_Cuestionario", typeof(bool));
    
            var u_FechaCuestionarioInicioParameter = u_FechaCuestionarioInicio.HasValue ?
                new ObjectParameter("U_FechaCuestionarioInicio", u_FechaCuestionarioInicio) :
                new ObjectParameter("U_FechaCuestionarioInicio", typeof(System.DateTime));
    
            var u_FechaCuestionarioFinParameter = u_FechaCuestionarioFin.HasValue ?
                new ObjectParameter("U_FechaCuestionarioFin", u_FechaCuestionarioFin) :
                new ObjectParameter("U_FechaCuestionarioFin", typeof(System.DateTime));
    
            var u_VacunacionParameter = u_Vacunacion.HasValue ?
                new ObjectParameter("U_Vacunacion", u_Vacunacion) :
                new ObjectParameter("U_Vacunacion", typeof(bool));
    
            var u_NroDosisParameter = u_NroDosis.HasValue ?
                new ObjectParameter("U_NroDosis", u_NroDosis) :
                new ObjectParameter("U_NroDosis", typeof(int));
    
            var u_SCTRParameter = u_SCTR.HasValue ?
                new ObjectParameter("U_SCTR", u_SCTR) :
                new ObjectParameter("U_SCTR", typeof(bool));
    
            var u_FechaSCTRInicioParameter = u_FechaSCTRInicio.HasValue ?
                new ObjectParameter("U_FechaSCTRInicio", u_FechaSCTRInicio) :
                new ObjectParameter("U_FechaSCTRInicio", typeof(System.DateTime));
    
            var u_FechaSCTRFinParameter = u_FechaSCTRFin.HasValue ?
                new ObjectParameter("U_FechaSCTRFin", u_FechaSCTRFin) :
                new ObjectParameter("U_FechaSCTRFin", typeof(System.DateTime));
    
            var u_InduccionParameter = u_Induccion.HasValue ?
                new ObjectParameter("U_Induccion", u_Induccion) :
                new ObjectParameter("U_Induccion", typeof(bool));
    
            var u_LicenciaConducirParameter = u_LicenciaConducir.HasValue ?
                new ObjectParameter("U_LicenciaConducir", u_LicenciaConducir) :
                new ObjectParameter("U_LicenciaConducir", typeof(bool));
    
            var u_FechaLicenciaInicioParameter = u_FechaLicenciaInicio.HasValue ?
                new ObjectParameter("U_FechaLicenciaInicio", u_FechaLicenciaInicio) :
                new ObjectParameter("U_FechaLicenciaInicio", typeof(System.DateTime));
    
            var u_FechaLicenciaFinParameter = u_FechaLicenciaFin.HasValue ?
                new ObjectParameter("U_FechaLicenciaFin", u_FechaLicenciaFin) :
                new ObjectParameter("U_FechaLicenciaFin", typeof(System.DateTime));
    
            var u_EmailParameter = u_Email != null ?
                new ObjectParameter("U_Email", u_Email) :
                new ObjectParameter("U_Email", typeof(string));
    
            var u_ListaNegraParameter = u_ListaNegra.HasValue ?
                new ObjectParameter("U_ListaNegra", u_ListaNegra) :
                new ObjectParameter("U_ListaNegra", typeof(bool));
    
            var u_MotivoListaNegraParameter = u_MotivoListaNegra != null ?
                new ObjectParameter("U_MotivoListaNegra", u_MotivoListaNegra) :
                new ObjectParameter("U_MotivoListaNegra", typeof(string));
    
            var u_FechaListaNegraParameter = u_FechaListaNegra.HasValue ?
                new ObjectParameter("U_FechaListaNegra", u_FechaListaNegra) :
                new ObjectParameter("U_FechaListaNegra", typeof(System.DateTime));
    
            var u_SancionadoParameter = u_Sancionado.HasValue ?
                new ObjectParameter("U_Sancionado", u_Sancionado) :
                new ObjectParameter("U_Sancionado", typeof(bool));
    
            var u_FechaSancionInicioParameter = u_FechaSancionInicio.HasValue ?
                new ObjectParameter("U_FechaSancionInicio", u_FechaSancionInicio) :
                new ObjectParameter("U_FechaSancionInicio", typeof(System.DateTime));
    
            var u_FechaSancionFinParameter = u_FechaSancionFin.HasValue ?
                new ObjectParameter("U_FechaSancionFin", u_FechaSancionFin) :
                new ObjectParameter("U_FechaSancionFin", typeof(System.DateTime));
    
            var u_UsuarioRegistroParameter = u_UsuarioRegistro != null ?
                new ObjectParameter("U_UsuarioRegistro", u_UsuarioRegistro) :
                new ObjectParameter("U_UsuarioRegistro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_Personal", u_TipoDocumentoParameter, u_DocIdentidadParameter, u_NombreParameter, u_ApellidosParameter, u_CodEmpresaParameter, u_CuestionarioParameter, u_FechaCuestionarioInicioParameter, u_FechaCuestionarioFinParameter, u_VacunacionParameter, u_NroDosisParameter, u_SCTRParameter, u_FechaSCTRInicioParameter, u_FechaSCTRFinParameter, u_InduccionParameter, u_LicenciaConducirParameter, u_FechaLicenciaInicioParameter, u_FechaLicenciaFinParameter, u_EmailParameter, u_ListaNegraParameter, u_MotivoListaNegraParameter, u_FechaListaNegraParameter, u_SancionadoParameter, u_FechaSancionInicioParameter, u_FechaSancionFinParameter, u_UsuarioRegistroParameter, rpta, valRpta);
        }
    
        public virtual int UPDATE_Usuario(Nullable<int> code, string u_Apellidos, string u_Nombres, string u_Email, Nullable<bool> u_FlagActivo, Nullable<bool> u_SuperUsuario, Nullable<bool> u_Web, Nullable<bool> u_APP, string u_CodEmpresa, string u_UsuarioModificacion, ObjectParameter rpta)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(int));
    
            var u_ApellidosParameter = u_Apellidos != null ?
                new ObjectParameter("U_Apellidos", u_Apellidos) :
                new ObjectParameter("U_Apellidos", typeof(string));
    
            var u_NombresParameter = u_Nombres != null ?
                new ObjectParameter("U_Nombres", u_Nombres) :
                new ObjectParameter("U_Nombres", typeof(string));
    
            var u_EmailParameter = u_Email != null ?
                new ObjectParameter("U_Email", u_Email) :
                new ObjectParameter("U_Email", typeof(string));
    
            var u_FlagActivoParameter = u_FlagActivo.HasValue ?
                new ObjectParameter("U_FlagActivo", u_FlagActivo) :
                new ObjectParameter("U_FlagActivo", typeof(bool));
    
            var u_SuperUsuarioParameter = u_SuperUsuario.HasValue ?
                new ObjectParameter("U_SuperUsuario", u_SuperUsuario) :
                new ObjectParameter("U_SuperUsuario", typeof(bool));
    
            var u_WebParameter = u_Web.HasValue ?
                new ObjectParameter("U_Web", u_Web) :
                new ObjectParameter("U_Web", typeof(bool));
    
            var u_APPParameter = u_APP.HasValue ?
                new ObjectParameter("U_APP", u_APP) :
                new ObjectParameter("U_APP", typeof(bool));
    
            var u_CodEmpresaParameter = u_CodEmpresa != null ?
                new ObjectParameter("U_CodEmpresa", u_CodEmpresa) :
                new ObjectParameter("U_CodEmpresa", typeof(string));
    
            var u_UsuarioModificacionParameter = u_UsuarioModificacion != null ?
                new ObjectParameter("U_UsuarioModificacion", u_UsuarioModificacion) :
                new ObjectParameter("U_UsuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_Usuario", codeParameter, u_ApellidosParameter, u_NombresParameter, u_EmailParameter, u_FlagActivoParameter, u_SuperUsuarioParameter, u_WebParameter, u_APPParameter, u_CodEmpresaParameter, u_UsuarioModificacionParameter, rpta);
        }
    
        public virtual ObjectResult<USP_Web_Listar_TipoEmpresa_Result> GET_Listar_TipoEmpresa(Nullable<int> u_Cod)
        {
            var u_CodParameter = u_Cod.HasValue ?
                new ObjectParameter("U_Cod", u_Cod) :
                new ObjectParameter("U_Cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_TipoEmpresa_Result>("GET_Listar_TipoEmpresa", u_CodParameter);
        }
    
        public virtual int UPDATE_Transportista(Nullable<int> code, string u_Transportista, string u_CodEmpresa, string u_RUC, string u_Contacto, string u_FonoContacto, Nullable<bool> u_FlagActivo, string u_UsuarioRegistro, ObjectParameter rpta)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(int));
    
            var u_TransportistaParameter = u_Transportista != null ?
                new ObjectParameter("U_Transportista", u_Transportista) :
                new ObjectParameter("U_Transportista", typeof(string));
    
            var u_CodEmpresaParameter = u_CodEmpresa != null ?
                new ObjectParameter("U_CodEmpresa", u_CodEmpresa) :
                new ObjectParameter("U_CodEmpresa", typeof(string));
    
            var u_RUCParameter = u_RUC != null ?
                new ObjectParameter("U_RUC", u_RUC) :
                new ObjectParameter("U_RUC", typeof(string));
    
            var u_ContactoParameter = u_Contacto != null ?
                new ObjectParameter("U_Contacto", u_Contacto) :
                new ObjectParameter("U_Contacto", typeof(string));
    
            var u_FonoContactoParameter = u_FonoContacto != null ?
                new ObjectParameter("U_FonoContacto", u_FonoContacto) :
                new ObjectParameter("U_FonoContacto", typeof(string));
    
            var u_FlagActivoParameter = u_FlagActivo.HasValue ?
                new ObjectParameter("U_FlagActivo", u_FlagActivo) :
                new ObjectParameter("U_FlagActivo", typeof(bool));
    
            var u_UsuarioRegistroParameter = u_UsuarioRegistro != null ?
                new ObjectParameter("U_UsuarioRegistro", u_UsuarioRegistro) :
                new ObjectParameter("U_UsuarioRegistro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_Transportista", codeParameter, u_TransportistaParameter, u_CodEmpresaParameter, u_RUCParameter, u_ContactoParameter, u_FonoContactoParameter, u_FlagActivoParameter, u_UsuarioRegistroParameter, rpta);
        }
    
        public virtual int POST_Transportista(string u_CodTransportista, string u_Transportista, string u_CodEmpresa, string u_RUC, string u_Contacto, string u_FonoContacto, Nullable<bool> u_FlagActivo, string u_UsuarioRegistro, ObjectParameter rpta)
        {
            var u_CodTransportistaParameter = u_CodTransportista != null ?
                new ObjectParameter("U_CodTransportista", u_CodTransportista) :
                new ObjectParameter("U_CodTransportista", typeof(string));
    
            var u_TransportistaParameter = u_Transportista != null ?
                new ObjectParameter("U_Transportista", u_Transportista) :
                new ObjectParameter("U_Transportista", typeof(string));
    
            var u_CodEmpresaParameter = u_CodEmpresa != null ?
                new ObjectParameter("U_CodEmpresa", u_CodEmpresa) :
                new ObjectParameter("U_CodEmpresa", typeof(string));
    
            var u_RUCParameter = u_RUC != null ?
                new ObjectParameter("U_RUC", u_RUC) :
                new ObjectParameter("U_RUC", typeof(string));
    
            var u_ContactoParameter = u_Contacto != null ?
                new ObjectParameter("U_Contacto", u_Contacto) :
                new ObjectParameter("U_Contacto", typeof(string));
    
            var u_FonoContactoParameter = u_FonoContacto != null ?
                new ObjectParameter("U_FonoContacto", u_FonoContacto) :
                new ObjectParameter("U_FonoContacto", typeof(string));
    
            var u_FlagActivoParameter = u_FlagActivo.HasValue ?
                new ObjectParameter("U_FlagActivo", u_FlagActivo) :
                new ObjectParameter("U_FlagActivo", typeof(bool));
    
            var u_UsuarioRegistroParameter = u_UsuarioRegistro != null ?
                new ObjectParameter("U_UsuarioRegistro", u_UsuarioRegistro) :
                new ObjectParameter("U_UsuarioRegistro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_Transportista", u_CodTransportistaParameter, u_TransportistaParameter, u_CodEmpresaParameter, u_RUCParameter, u_ContactoParameter, u_FonoContactoParameter, u_FlagActivoParameter, u_UsuarioRegistroParameter, rpta);
        }
    
        public virtual int POST_Empresa(string u_Empresa, string u_RUC, string u_Contacto, Nullable<int> u_CodTipoEmpresa, string u_FonoContacto, string u_UsuarioRegistro, ObjectParameter rpta)
        {
            var u_EmpresaParameter = u_Empresa != null ?
                new ObjectParameter("U_Empresa", u_Empresa) :
                new ObjectParameter("U_Empresa", typeof(string));
    
            var u_RUCParameter = u_RUC != null ?
                new ObjectParameter("U_RUC", u_RUC) :
                new ObjectParameter("U_RUC", typeof(string));
    
            var u_ContactoParameter = u_Contacto != null ?
                new ObjectParameter("U_Contacto", u_Contacto) :
                new ObjectParameter("U_Contacto", typeof(string));
    
            var u_CodTipoEmpresaParameter = u_CodTipoEmpresa.HasValue ?
                new ObjectParameter("U_CodTipoEmpresa", u_CodTipoEmpresa) :
                new ObjectParameter("U_CodTipoEmpresa", typeof(int));
    
            var u_FonoContactoParameter = u_FonoContacto != null ?
                new ObjectParameter("U_FonoContacto", u_FonoContacto) :
                new ObjectParameter("U_FonoContacto", typeof(string));
    
            var u_UsuarioRegistroParameter = u_UsuarioRegistro != null ?
                new ObjectParameter("U_UsuarioRegistro", u_UsuarioRegistro) :
                new ObjectParameter("U_UsuarioRegistro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_Empresa", u_EmpresaParameter, u_RUCParameter, u_ContactoParameter, u_CodTipoEmpresaParameter, u_FonoContactoParameter, u_UsuarioRegistroParameter, rpta);
        }
    
        public virtual ObjectResult<USP_Web_Listar_Empresa_Result> GET_Listar_Empresa(Nullable<int> u_Cod)
        {
            var u_CodParameter = u_Cod.HasValue ?
                new ObjectParameter("U_Cod", u_Cod) :
                new ObjectParameter("U_Cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_Empresa_Result>("GET_Listar_Empresa", u_CodParameter);
        }
    
        public virtual int POST_Conductor(Nullable<int> u_TipoDocumento, string u_DocIdentidad, string u_CodEmpresa, string u_Nombre, string u_Apellidos, string u_RutaCuestionario, string u_RutaVacunacion, string u_RutaSCTR, string u_RutaLicConducir, string u_UsuarioRegistro, ObjectParameter rpta, ObjectParameter valRpta)
        {
            var u_TipoDocumentoParameter = u_TipoDocumento.HasValue ?
                new ObjectParameter("U_TipoDocumento", u_TipoDocumento) :
                new ObjectParameter("U_TipoDocumento", typeof(int));
    
            var u_DocIdentidadParameter = u_DocIdentidad != null ?
                new ObjectParameter("U_DocIdentidad", u_DocIdentidad) :
                new ObjectParameter("U_DocIdentidad", typeof(string));
    
            var u_CodEmpresaParameter = u_CodEmpresa != null ?
                new ObjectParameter("U_CodEmpresa", u_CodEmpresa) :
                new ObjectParameter("U_CodEmpresa", typeof(string));
    
            var u_NombreParameter = u_Nombre != null ?
                new ObjectParameter("U_Nombre", u_Nombre) :
                new ObjectParameter("U_Nombre", typeof(string));
    
            var u_ApellidosParameter = u_Apellidos != null ?
                new ObjectParameter("U_Apellidos", u_Apellidos) :
                new ObjectParameter("U_Apellidos", typeof(string));
    
            var u_RutaCuestionarioParameter = u_RutaCuestionario != null ?
                new ObjectParameter("U_RutaCuestionario", u_RutaCuestionario) :
                new ObjectParameter("U_RutaCuestionario", typeof(string));
    
            var u_RutaVacunacionParameter = u_RutaVacunacion != null ?
                new ObjectParameter("U_RutaVacunacion", u_RutaVacunacion) :
                new ObjectParameter("U_RutaVacunacion", typeof(string));
    
            var u_RutaSCTRParameter = u_RutaSCTR != null ?
                new ObjectParameter("U_RutaSCTR", u_RutaSCTR) :
                new ObjectParameter("U_RutaSCTR", typeof(string));
    
            var u_RutaLicConducirParameter = u_RutaLicConducir != null ?
                new ObjectParameter("U_RutaLicConducir", u_RutaLicConducir) :
                new ObjectParameter("U_RutaLicConducir", typeof(string));
    
            var u_UsuarioRegistroParameter = u_UsuarioRegistro != null ?
                new ObjectParameter("U_UsuarioRegistro", u_UsuarioRegistro) :
                new ObjectParameter("U_UsuarioRegistro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_Conductor", u_TipoDocumentoParameter, u_DocIdentidadParameter, u_CodEmpresaParameter, u_NombreParameter, u_ApellidosParameter, u_RutaCuestionarioParameter, u_RutaVacunacionParameter, u_RutaSCTRParameter, u_RutaLicConducirParameter, u_UsuarioRegistroParameter, rpta, valRpta);
        }
    
        public virtual int UPDATE_Vehiculo(Nullable<long> u_IdTx, string u_CodEmpresa, string u_Anio, string u_Marca, string u_RutaRevTecnica, string u_RutaSOAT, string u_RutaTarjPropiedad, string u_UsuarioModificacion, ObjectParameter rpta)
        {
            var u_IdTxParameter = u_IdTx.HasValue ?
                new ObjectParameter("U_IdTx", u_IdTx) :
                new ObjectParameter("U_IdTx", typeof(long));
    
            var u_CodEmpresaParameter = u_CodEmpresa != null ?
                new ObjectParameter("U_CodEmpresa", u_CodEmpresa) :
                new ObjectParameter("U_CodEmpresa", typeof(string));
    
            var u_AnioParameter = u_Anio != null ?
                new ObjectParameter("U_Anio", u_Anio) :
                new ObjectParameter("U_Anio", typeof(string));
    
            var u_MarcaParameter = u_Marca != null ?
                new ObjectParameter("U_Marca", u_Marca) :
                new ObjectParameter("U_Marca", typeof(string));
    
            var u_RutaRevTecnicaParameter = u_RutaRevTecnica != null ?
                new ObjectParameter("U_RutaRevTecnica", u_RutaRevTecnica) :
                new ObjectParameter("U_RutaRevTecnica", typeof(string));
    
            var u_RutaSOATParameter = u_RutaSOAT != null ?
                new ObjectParameter("U_RutaSOAT", u_RutaSOAT) :
                new ObjectParameter("U_RutaSOAT", typeof(string));
    
            var u_RutaTarjPropiedadParameter = u_RutaTarjPropiedad != null ?
                new ObjectParameter("U_RutaTarjPropiedad", u_RutaTarjPropiedad) :
                new ObjectParameter("U_RutaTarjPropiedad", typeof(string));
    
            var u_UsuarioModificacionParameter = u_UsuarioModificacion != null ?
                new ObjectParameter("U_UsuarioModificacion", u_UsuarioModificacion) :
                new ObjectParameter("U_UsuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_Vehiculo", u_IdTxParameter, u_CodEmpresaParameter, u_AnioParameter, u_MarcaParameter, u_RutaRevTecnicaParameter, u_RutaSOATParameter, u_RutaTarjPropiedadParameter, u_UsuarioModificacionParameter, rpta);
        }
    
        public virtual int POST_Vehiculo(string u_CodEmpresa, string u_Placa, string u_Anio, string u_Marca, string u_RutaRevTecnica, string u_RutaSOAT, string u_RutaTarjPropiedad, string u_UsuarioRegistro, ObjectParameter valRpta, ObjectParameter rpta)
        {
            var u_CodEmpresaParameter = u_CodEmpresa != null ?
                new ObjectParameter("U_CodEmpresa", u_CodEmpresa) :
                new ObjectParameter("U_CodEmpresa", typeof(string));
    
            var u_PlacaParameter = u_Placa != null ?
                new ObjectParameter("U_Placa", u_Placa) :
                new ObjectParameter("U_Placa", typeof(string));
    
            var u_AnioParameter = u_Anio != null ?
                new ObjectParameter("U_Anio", u_Anio) :
                new ObjectParameter("U_Anio", typeof(string));
    
            var u_MarcaParameter = u_Marca != null ?
                new ObjectParameter("U_Marca", u_Marca) :
                new ObjectParameter("U_Marca", typeof(string));
    
            var u_RutaRevTecnicaParameter = u_RutaRevTecnica != null ?
                new ObjectParameter("U_RutaRevTecnica", u_RutaRevTecnica) :
                new ObjectParameter("U_RutaRevTecnica", typeof(string));
    
            var u_RutaSOATParameter = u_RutaSOAT != null ?
                new ObjectParameter("U_RutaSOAT", u_RutaSOAT) :
                new ObjectParameter("U_RutaSOAT", typeof(string));
    
            var u_RutaTarjPropiedadParameter = u_RutaTarjPropiedad != null ?
                new ObjectParameter("U_RutaTarjPropiedad", u_RutaTarjPropiedad) :
                new ObjectParameter("U_RutaTarjPropiedad", typeof(string));
    
            var u_UsuarioRegistroParameter = u_UsuarioRegistro != null ?
                new ObjectParameter("U_UsuarioRegistro", u_UsuarioRegistro) :
                new ObjectParameter("U_UsuarioRegistro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_Vehiculo", u_CodEmpresaParameter, u_PlacaParameter, u_AnioParameter, u_MarcaParameter, u_RutaRevTecnicaParameter, u_RutaSOATParameter, u_RutaTarjPropiedadParameter, u_UsuarioRegistroParameter, valRpta, rpta);
        }
    
        public virtual int UPDATE_Empresa(Nullable<int> code, string u_Empresa, string u_RUC, string u_Contacto, Nullable<int> u_CodTipoEmpresa, string u_FonoContacto, string u_UsuarioModificacion, Nullable<bool> u_FlagActivo, ObjectParameter rpta)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(int));
    
            var u_EmpresaParameter = u_Empresa != null ?
                new ObjectParameter("U_Empresa", u_Empresa) :
                new ObjectParameter("U_Empresa", typeof(string));
    
            var u_RUCParameter = u_RUC != null ?
                new ObjectParameter("U_RUC", u_RUC) :
                new ObjectParameter("U_RUC", typeof(string));
    
            var u_ContactoParameter = u_Contacto != null ?
                new ObjectParameter("U_Contacto", u_Contacto) :
                new ObjectParameter("U_Contacto", typeof(string));
    
            var u_CodTipoEmpresaParameter = u_CodTipoEmpresa.HasValue ?
                new ObjectParameter("U_CodTipoEmpresa", u_CodTipoEmpresa) :
                new ObjectParameter("U_CodTipoEmpresa", typeof(int));
    
            var u_FonoContactoParameter = u_FonoContacto != null ?
                new ObjectParameter("U_FonoContacto", u_FonoContacto) :
                new ObjectParameter("U_FonoContacto", typeof(string));
    
            var u_UsuarioModificacionParameter = u_UsuarioModificacion != null ?
                new ObjectParameter("U_UsuarioModificacion", u_UsuarioModificacion) :
                new ObjectParameter("U_UsuarioModificacion", typeof(string));
    
            var u_FlagActivoParameter = u_FlagActivo.HasValue ?
                new ObjectParameter("U_FlagActivo", u_FlagActivo) :
                new ObjectParameter("U_FlagActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_Empresa", codeParameter, u_EmpresaParameter, u_RUCParameter, u_ContactoParameter, u_CodTipoEmpresaParameter, u_FonoContactoParameter, u_UsuarioModificacionParameter, u_FlagActivoParameter, rpta);
        }
    
        public virtual int UPDATE_Personal(Nullable<long> u_IdTx, string u_Nombre, string u_Apellidos, string u_CodEmpresa, Nullable<System.DateTime> u_FechaCuestionarioInicio, Nullable<System.DateTime> u_FechaCuestionarioFin, Nullable<bool> u_Vacunacion, Nullable<System.DateTime> u_FechaSCTRInicio, Nullable<System.DateTime> u_FechaSCTRFin, Nullable<bool> u_Induccion, Nullable<System.DateTime> u_FechaLicenciaInicio, Nullable<System.DateTime> u_FechaLicenciaFin, string u_Email, Nullable<bool> u_ListaNegra, string u_MotivoListaNegra, Nullable<System.DateTime> u_FechaListaNegra, Nullable<bool> u_Sancionado, Nullable<System.DateTime> u_FechaSancionInicio, Nullable<System.DateTime> u_Fecha_SancionFin, Nullable<bool> u_Cuestionario, Nullable<int> u_NroDosis, Nullable<bool> u_SCTR, Nullable<bool> u_LicenciaConducir, string u_UsuarioModificacion, ObjectParameter rpta)
        {
            var u_IdTxParameter = u_IdTx.HasValue ?
                new ObjectParameter("U_IdTx", u_IdTx) :
                new ObjectParameter("U_IdTx", typeof(long));
    
            var u_NombreParameter = u_Nombre != null ?
                new ObjectParameter("U_Nombre", u_Nombre) :
                new ObjectParameter("U_Nombre", typeof(string));
    
            var u_ApellidosParameter = u_Apellidos != null ?
                new ObjectParameter("U_Apellidos", u_Apellidos) :
                new ObjectParameter("U_Apellidos", typeof(string));
    
            var u_CodEmpresaParameter = u_CodEmpresa != null ?
                new ObjectParameter("U_CodEmpresa", u_CodEmpresa) :
                new ObjectParameter("U_CodEmpresa", typeof(string));
    
            var u_FechaCuestionarioInicioParameter = u_FechaCuestionarioInicio.HasValue ?
                new ObjectParameter("U_FechaCuestionarioInicio", u_FechaCuestionarioInicio) :
                new ObjectParameter("U_FechaCuestionarioInicio", typeof(System.DateTime));
    
            var u_FechaCuestionarioFinParameter = u_FechaCuestionarioFin.HasValue ?
                new ObjectParameter("U_FechaCuestionarioFin", u_FechaCuestionarioFin) :
                new ObjectParameter("U_FechaCuestionarioFin", typeof(System.DateTime));
    
            var u_VacunacionParameter = u_Vacunacion.HasValue ?
                new ObjectParameter("U_Vacunacion", u_Vacunacion) :
                new ObjectParameter("U_Vacunacion", typeof(bool));
    
            var u_FechaSCTRInicioParameter = u_FechaSCTRInicio.HasValue ?
                new ObjectParameter("U_FechaSCTRInicio", u_FechaSCTRInicio) :
                new ObjectParameter("U_FechaSCTRInicio", typeof(System.DateTime));
    
            var u_FechaSCTRFinParameter = u_FechaSCTRFin.HasValue ?
                new ObjectParameter("U_FechaSCTRFin", u_FechaSCTRFin) :
                new ObjectParameter("U_FechaSCTRFin", typeof(System.DateTime));
    
            var u_InduccionParameter = u_Induccion.HasValue ?
                new ObjectParameter("U_Induccion", u_Induccion) :
                new ObjectParameter("U_Induccion", typeof(bool));
    
            var u_FechaLicenciaInicioParameter = u_FechaLicenciaInicio.HasValue ?
                new ObjectParameter("U_FechaLicenciaInicio", u_FechaLicenciaInicio) :
                new ObjectParameter("U_FechaLicenciaInicio", typeof(System.DateTime));
    
            var u_FechaLicenciaFinParameter = u_FechaLicenciaFin.HasValue ?
                new ObjectParameter("U_FechaLicenciaFin", u_FechaLicenciaFin) :
                new ObjectParameter("U_FechaLicenciaFin", typeof(System.DateTime));
    
            var u_EmailParameter = u_Email != null ?
                new ObjectParameter("U_Email", u_Email) :
                new ObjectParameter("U_Email", typeof(string));
    
            var u_ListaNegraParameter = u_ListaNegra.HasValue ?
                new ObjectParameter("U_ListaNegra", u_ListaNegra) :
                new ObjectParameter("U_ListaNegra", typeof(bool));
    
            var u_MotivoListaNegraParameter = u_MotivoListaNegra != null ?
                new ObjectParameter("U_MotivoListaNegra", u_MotivoListaNegra) :
                new ObjectParameter("U_MotivoListaNegra", typeof(string));
    
            var u_FechaListaNegraParameter = u_FechaListaNegra.HasValue ?
                new ObjectParameter("U_FechaListaNegra", u_FechaListaNegra) :
                new ObjectParameter("U_FechaListaNegra", typeof(System.DateTime));
    
            var u_SancionadoParameter = u_Sancionado.HasValue ?
                new ObjectParameter("U_Sancionado", u_Sancionado) :
                new ObjectParameter("U_Sancionado", typeof(bool));
    
            var u_FechaSancionInicioParameter = u_FechaSancionInicio.HasValue ?
                new ObjectParameter("U_FechaSancionInicio", u_FechaSancionInicio) :
                new ObjectParameter("U_FechaSancionInicio", typeof(System.DateTime));
    
            var u_Fecha_SancionFinParameter = u_Fecha_SancionFin.HasValue ?
                new ObjectParameter("U_Fecha_SancionFin", u_Fecha_SancionFin) :
                new ObjectParameter("U_Fecha_SancionFin", typeof(System.DateTime));
    
            var u_CuestionarioParameter = u_Cuestionario.HasValue ?
                new ObjectParameter("U_Cuestionario", u_Cuestionario) :
                new ObjectParameter("U_Cuestionario", typeof(bool));
    
            var u_NroDosisParameter = u_NroDosis.HasValue ?
                new ObjectParameter("U_NroDosis", u_NroDosis) :
                new ObjectParameter("U_NroDosis", typeof(int));
    
            var u_SCTRParameter = u_SCTR.HasValue ?
                new ObjectParameter("U_SCTR", u_SCTR) :
                new ObjectParameter("U_SCTR", typeof(bool));
    
            var u_LicenciaConducirParameter = u_LicenciaConducir.HasValue ?
                new ObjectParameter("U_LicenciaConducir", u_LicenciaConducir) :
                new ObjectParameter("U_LicenciaConducir", typeof(bool));
    
            var u_UsuarioModificacionParameter = u_UsuarioModificacion != null ?
                new ObjectParameter("U_UsuarioModificacion", u_UsuarioModificacion) :
                new ObjectParameter("U_UsuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_Personal", u_IdTxParameter, u_NombreParameter, u_ApellidosParameter, u_CodEmpresaParameter, u_FechaCuestionarioInicioParameter, u_FechaCuestionarioFinParameter, u_VacunacionParameter, u_FechaSCTRInicioParameter, u_FechaSCTRFinParameter, u_InduccionParameter, u_FechaLicenciaInicioParameter, u_FechaLicenciaFinParameter, u_EmailParameter, u_ListaNegraParameter, u_MotivoListaNegraParameter, u_FechaListaNegraParameter, u_SancionadoParameter, u_FechaSancionInicioParameter, u_Fecha_SancionFinParameter, u_CuestionarioParameter, u_NroDosisParameter, u_SCTRParameter, u_LicenciaConducirParameter, u_UsuarioModificacionParameter, rpta);
        }
    
        public virtual ObjectResult<USP_Web_Listar_Personal_Result> GET_Listar_Personal(Nullable<int> code, string busqGral)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(int));
    
            var busqGralParameter = busqGral != null ?
                new ObjectParameter("busqGral", busqGral) :
                new ObjectParameter("busqGral", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_Personal_Result>("GET_Listar_Personal", codeParameter, busqGralParameter);
        }
    
        public virtual int UPDATE_PersonalAsistencia_Salida(Nullable<int> u_NroDocumento, string u_ObservacionSalida, string u_UsuarioModificacion, Nullable<bool> u_DevuelveLlave, ObjectParameter rpta, ObjectParameter valRpta)
        {
            var u_NroDocumentoParameter = u_NroDocumento.HasValue ?
                new ObjectParameter("U_NroDocumento", u_NroDocumento) :
                new ObjectParameter("U_NroDocumento", typeof(int));
    
            var u_ObservacionSalidaParameter = u_ObservacionSalida != null ?
                new ObjectParameter("U_ObservacionSalida", u_ObservacionSalida) :
                new ObjectParameter("U_ObservacionSalida", typeof(string));
    
            var u_UsuarioModificacionParameter = u_UsuarioModificacion != null ?
                new ObjectParameter("U_UsuarioModificacion", u_UsuarioModificacion) :
                new ObjectParameter("U_UsuarioModificacion", typeof(string));
    
            var u_DevuelveLlaveParameter = u_DevuelveLlave.HasValue ?
                new ObjectParameter("U_DevuelveLlave", u_DevuelveLlave) :
                new ObjectParameter("U_DevuelveLlave", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_PersonalAsistencia_Salida", u_NroDocumentoParameter, u_ObservacionSalidaParameter, u_UsuarioModificacionParameter, u_DevuelveLlaveParameter, rpta, valRpta);
        }
    
        public virtual int POST_PersonalAsistencia_Cab(string u_CodEmpresa, Nullable<int> u_CodPersonal, string u_ObservacionIngreso, Nullable<int> u_TipoAsistencia, Nullable<bool> u_EntregaLlave, string u_OficinaLlave, string u_CodAutorizante, string u_MotivoAutorizacion, string u_UsuarioRegistro, ObjectParameter rpta, ObjectParameter valRpta)
        {
            var u_CodEmpresaParameter = u_CodEmpresa != null ?
                new ObjectParameter("U_CodEmpresa", u_CodEmpresa) :
                new ObjectParameter("U_CodEmpresa", typeof(string));
    
            var u_CodPersonalParameter = u_CodPersonal.HasValue ?
                new ObjectParameter("U_CodPersonal", u_CodPersonal) :
                new ObjectParameter("U_CodPersonal", typeof(int));
    
            var u_ObservacionIngresoParameter = u_ObservacionIngreso != null ?
                new ObjectParameter("U_ObservacionIngreso", u_ObservacionIngreso) :
                new ObjectParameter("U_ObservacionIngreso", typeof(string));
    
            var u_TipoAsistenciaParameter = u_TipoAsistencia.HasValue ?
                new ObjectParameter("U_TipoAsistencia", u_TipoAsistencia) :
                new ObjectParameter("U_TipoAsistencia", typeof(int));
    
            var u_EntregaLlaveParameter = u_EntregaLlave.HasValue ?
                new ObjectParameter("U_EntregaLlave", u_EntregaLlave) :
                new ObjectParameter("U_EntregaLlave", typeof(bool));
    
            var u_OficinaLlaveParameter = u_OficinaLlave != null ?
                new ObjectParameter("U_OficinaLlave", u_OficinaLlave) :
                new ObjectParameter("U_OficinaLlave", typeof(string));
    
            var u_CodAutorizanteParameter = u_CodAutorizante != null ?
                new ObjectParameter("U_CodAutorizante", u_CodAutorizante) :
                new ObjectParameter("U_CodAutorizante", typeof(string));
    
            var u_MotivoAutorizacionParameter = u_MotivoAutorizacion != null ?
                new ObjectParameter("U_MotivoAutorizacion", u_MotivoAutorizacion) :
                new ObjectParameter("U_MotivoAutorizacion", typeof(string));
    
            var u_UsuarioRegistroParameter = u_UsuarioRegistro != null ?
                new ObjectParameter("U_UsuarioRegistro", u_UsuarioRegistro) :
                new ObjectParameter("U_UsuarioRegistro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_PersonalAsistencia_Cab", u_CodEmpresaParameter, u_CodPersonalParameter, u_ObservacionIngresoParameter, u_TipoAsistenciaParameter, u_EntregaLlaveParameter, u_OficinaLlaveParameter, u_CodAutorizanteParameter, u_MotivoAutorizacionParameter, u_UsuarioRegistroParameter, rpta, valRpta);
        }
    
        public virtual ObjectResult<USP_Web_Listar_DatosInicialesUsuario_Result> GET_Listar_DatosInicialesUsuario(string userCode, string userPassword)
        {
            var userCodeParameter = userCode != null ?
                new ObjectParameter("UserCode", userCode) :
                new ObjectParameter("UserCode", typeof(string));
    
            var userPasswordParameter = userPassword != null ?
                new ObjectParameter("UserPassword", userPassword) :
                new ObjectParameter("UserPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_DatosInicialesUsuario_Result>("GET_Listar_DatosInicialesUsuario", userCodeParameter, userPasswordParameter);
        }
    
        public virtual ObjectResult<USP_Web_Listar_TipoIngreso_Result> GET_Listar_TipoIngreso()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_TipoIngreso_Result>("GET_Listar_TipoIngreso");
        }
    
        public virtual ObjectResult<USP_Web_Listar_Usuarios_Result> GET_Listar_Usuarios(Nullable<int> code)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_Usuarios_Result>("GET_Listar_Usuarios", codeParameter);
        }
    
        public virtual ObjectResult<USP_Web_Listar_Vehiculo_Result> GET_Listar_Vehiculo(Nullable<int> u_Cod, string busqGral, string codEmpresa)
        {
            var u_CodParameter = u_Cod.HasValue ?
                new ObjectParameter("U_Cod", u_Cod) :
                new ObjectParameter("U_Cod", typeof(int));
    
            var busqGralParameter = busqGral != null ?
                new ObjectParameter("busqGral", busqGral) :
                new ObjectParameter("busqGral", typeof(string));
    
            var codEmpresaParameter = codEmpresa != null ?
                new ObjectParameter("CodEmpresa", codEmpresa) :
                new ObjectParameter("CodEmpresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_Vehiculo_Result>("GET_Listar_Vehiculo", u_CodParameter, busqGralParameter, codEmpresaParameter);
        }
    
        public virtual int POST_Ayudante(Nullable<int> u_TipoDocumento, string u_DocIdentidad, string u_CodEmpresa, string u_Nombre, string u_Apellidos, string u_RutaCuestionario, string u_RutaVacunacion, string u_RutaSCTR, string u_RutaInduccion, string u_UsuarioRegistro, ObjectParameter rpta, ObjectParameter valRpta)
        {
            var u_TipoDocumentoParameter = u_TipoDocumento.HasValue ?
                new ObjectParameter("U_TipoDocumento", u_TipoDocumento) :
                new ObjectParameter("U_TipoDocumento", typeof(int));
    
            var u_DocIdentidadParameter = u_DocIdentidad != null ?
                new ObjectParameter("U_DocIdentidad", u_DocIdentidad) :
                new ObjectParameter("U_DocIdentidad", typeof(string));
    
            var u_CodEmpresaParameter = u_CodEmpresa != null ?
                new ObjectParameter("U_CodEmpresa", u_CodEmpresa) :
                new ObjectParameter("U_CodEmpresa", typeof(string));
    
            var u_NombreParameter = u_Nombre != null ?
                new ObjectParameter("U_Nombre", u_Nombre) :
                new ObjectParameter("U_Nombre", typeof(string));
    
            var u_ApellidosParameter = u_Apellidos != null ?
                new ObjectParameter("U_Apellidos", u_Apellidos) :
                new ObjectParameter("U_Apellidos", typeof(string));
    
            var u_RutaCuestionarioParameter = u_RutaCuestionario != null ?
                new ObjectParameter("U_RutaCuestionario", u_RutaCuestionario) :
                new ObjectParameter("U_RutaCuestionario", typeof(string));
    
            var u_RutaVacunacionParameter = u_RutaVacunacion != null ?
                new ObjectParameter("U_RutaVacunacion", u_RutaVacunacion) :
                new ObjectParameter("U_RutaVacunacion", typeof(string));
    
            var u_RutaSCTRParameter = u_RutaSCTR != null ?
                new ObjectParameter("U_RutaSCTR", u_RutaSCTR) :
                new ObjectParameter("U_RutaSCTR", typeof(string));
    
            var u_RutaInduccionParameter = u_RutaInduccion != null ?
                new ObjectParameter("U_RutaInduccion", u_RutaInduccion) :
                new ObjectParameter("U_RutaInduccion", typeof(string));
    
            var u_UsuarioRegistroParameter = u_UsuarioRegistro != null ?
                new ObjectParameter("U_UsuarioRegistro", u_UsuarioRegistro) :
                new ObjectParameter("U_UsuarioRegistro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_Ayudante", u_TipoDocumentoParameter, u_DocIdentidadParameter, u_CodEmpresaParameter, u_NombreParameter, u_ApellidosParameter, u_RutaCuestionarioParameter, u_RutaVacunacionParameter, u_RutaSCTRParameter, u_RutaInduccionParameter, u_UsuarioRegistroParameter, rpta, valRpta);
        }
    
        public virtual int UPDATE_Ayudante(Nullable<long> u_IdTx, string u_Nombre, string u_Apellidos, string u_RutaCuestionario, string u_RutaVacunacion, string u_RutaSCTR, string u_RutaInduccion, string u_UsuarioModificacion, Nullable<bool> u_FlagActivo, ObjectParameter rpta)
        {
            var u_IdTxParameter = u_IdTx.HasValue ?
                new ObjectParameter("U_IdTx", u_IdTx) :
                new ObjectParameter("U_IdTx", typeof(long));
    
            var u_NombreParameter = u_Nombre != null ?
                new ObjectParameter("U_Nombre", u_Nombre) :
                new ObjectParameter("U_Nombre", typeof(string));
    
            var u_ApellidosParameter = u_Apellidos != null ?
                new ObjectParameter("U_Apellidos", u_Apellidos) :
                new ObjectParameter("U_Apellidos", typeof(string));
    
            var u_RutaCuestionarioParameter = u_RutaCuestionario != null ?
                new ObjectParameter("U_RutaCuestionario", u_RutaCuestionario) :
                new ObjectParameter("U_RutaCuestionario", typeof(string));
    
            var u_RutaVacunacionParameter = u_RutaVacunacion != null ?
                new ObjectParameter("U_RutaVacunacion", u_RutaVacunacion) :
                new ObjectParameter("U_RutaVacunacion", typeof(string));
    
            var u_RutaSCTRParameter = u_RutaSCTR != null ?
                new ObjectParameter("U_RutaSCTR", u_RutaSCTR) :
                new ObjectParameter("U_RutaSCTR", typeof(string));
    
            var u_RutaInduccionParameter = u_RutaInduccion != null ?
                new ObjectParameter("U_RutaInduccion", u_RutaInduccion) :
                new ObjectParameter("U_RutaInduccion", typeof(string));
    
            var u_UsuarioModificacionParameter = u_UsuarioModificacion != null ?
                new ObjectParameter("U_UsuarioModificacion", u_UsuarioModificacion) :
                new ObjectParameter("U_UsuarioModificacion", typeof(string));
    
            var u_FlagActivoParameter = u_FlagActivo.HasValue ?
                new ObjectParameter("U_FlagActivo", u_FlagActivo) :
                new ObjectParameter("U_FlagActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_Ayudante", u_IdTxParameter, u_NombreParameter, u_ApellidosParameter, u_RutaCuestionarioParameter, u_RutaVacunacionParameter, u_RutaSCTRParameter, u_RutaInduccionParameter, u_UsuarioModificacionParameter, u_FlagActivoParameter, rpta);
        }
    
        public virtual int UPDATE_Conductor(Nullable<long> u_IdTx, string u_CodEmpresa, string u_Nombre, string u_Apellidos, string u_RutaCuestionario, string u_RutaVacunacion, string u_RutaSCTR, string u_RutaLicConducir, string u_UsuarioModificacion, Nullable<bool> u_FlagActivo, ObjectParameter rpta)
        {
            var u_IdTxParameter = u_IdTx.HasValue ?
                new ObjectParameter("U_IdTx", u_IdTx) :
                new ObjectParameter("U_IdTx", typeof(long));
    
            var u_CodEmpresaParameter = u_CodEmpresa != null ?
                new ObjectParameter("U_CodEmpresa", u_CodEmpresa) :
                new ObjectParameter("U_CodEmpresa", typeof(string));
    
            var u_NombreParameter = u_Nombre != null ?
                new ObjectParameter("U_Nombre", u_Nombre) :
                new ObjectParameter("U_Nombre", typeof(string));
    
            var u_ApellidosParameter = u_Apellidos != null ?
                new ObjectParameter("U_Apellidos", u_Apellidos) :
                new ObjectParameter("U_Apellidos", typeof(string));
    
            var u_RutaCuestionarioParameter = u_RutaCuestionario != null ?
                new ObjectParameter("U_RutaCuestionario", u_RutaCuestionario) :
                new ObjectParameter("U_RutaCuestionario", typeof(string));
    
            var u_RutaVacunacionParameter = u_RutaVacunacion != null ?
                new ObjectParameter("U_RutaVacunacion", u_RutaVacunacion) :
                new ObjectParameter("U_RutaVacunacion", typeof(string));
    
            var u_RutaSCTRParameter = u_RutaSCTR != null ?
                new ObjectParameter("U_RutaSCTR", u_RutaSCTR) :
                new ObjectParameter("U_RutaSCTR", typeof(string));
    
            var u_RutaLicConducirParameter = u_RutaLicConducir != null ?
                new ObjectParameter("U_RutaLicConducir", u_RutaLicConducir) :
                new ObjectParameter("U_RutaLicConducir", typeof(string));
    
            var u_UsuarioModificacionParameter = u_UsuarioModificacion != null ?
                new ObjectParameter("U_UsuarioModificacion", u_UsuarioModificacion) :
                new ObjectParameter("U_UsuarioModificacion", typeof(string));
    
            var u_FlagActivoParameter = u_FlagActivo.HasValue ?
                new ObjectParameter("U_FlagActivo", u_FlagActivo) :
                new ObjectParameter("U_FlagActivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_Conductor", u_IdTxParameter, u_CodEmpresaParameter, u_NombreParameter, u_ApellidosParameter, u_RutaCuestionarioParameter, u_RutaVacunacionParameter, u_RutaSCTRParameter, u_RutaLicConducirParameter, u_UsuarioModificacionParameter, u_FlagActivoParameter, rpta);
        }
    
        public virtual ObjectResult<USP_Web_Listar_PersonalAsistencia_Cab_Result> GET_Listar_PersonalAsistencia_Cab(string fechaIni, string fechaFin, string busqGral)
        {
            var fechaIniParameter = fechaIni != null ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(string));
    
            var fechaFinParameter = fechaFin != null ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(string));
    
            var busqGralParameter = busqGral != null ?
                new ObjectParameter("busqGral", busqGral) :
                new ObjectParameter("busqGral", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_PersonalAsistencia_Cab_Result>("GET_Listar_PersonalAsistencia_Cab", fechaIniParameter, fechaFinParameter, busqGralParameter);
        }
    
        public virtual int POST_Usuario(string u_CodUsuario, string u_Contrasena, string u_Nombres, string u_Apellidos, string u_Email, Nullable<bool> u_SuperUsuario, Nullable<bool> u_Web, Nullable<bool> u_APP, string u_UsuarioRegistro, string u_CodEmpresa, ObjectParameter rpta)
        {
            var u_CodUsuarioParameter = u_CodUsuario != null ?
                new ObjectParameter("U_CodUsuario", u_CodUsuario) :
                new ObjectParameter("U_CodUsuario", typeof(string));
    
            var u_ContrasenaParameter = u_Contrasena != null ?
                new ObjectParameter("U_Contrasena", u_Contrasena) :
                new ObjectParameter("U_Contrasena", typeof(string));
    
            var u_NombresParameter = u_Nombres != null ?
                new ObjectParameter("U_Nombres", u_Nombres) :
                new ObjectParameter("U_Nombres", typeof(string));
    
            var u_ApellidosParameter = u_Apellidos != null ?
                new ObjectParameter("U_Apellidos", u_Apellidos) :
                new ObjectParameter("U_Apellidos", typeof(string));
    
            var u_EmailParameter = u_Email != null ?
                new ObjectParameter("U_Email", u_Email) :
                new ObjectParameter("U_Email", typeof(string));
    
            var u_SuperUsuarioParameter = u_SuperUsuario.HasValue ?
                new ObjectParameter("U_SuperUsuario", u_SuperUsuario) :
                new ObjectParameter("U_SuperUsuario", typeof(bool));
    
            var u_WebParameter = u_Web.HasValue ?
                new ObjectParameter("U_Web", u_Web) :
                new ObjectParameter("U_Web", typeof(bool));
    
            var u_APPParameter = u_APP.HasValue ?
                new ObjectParameter("U_APP", u_APP) :
                new ObjectParameter("U_APP", typeof(bool));
    
            var u_UsuarioRegistroParameter = u_UsuarioRegistro != null ?
                new ObjectParameter("U_UsuarioRegistro", u_UsuarioRegistro) :
                new ObjectParameter("U_UsuarioRegistro", typeof(string));
    
            var u_CodEmpresaParameter = u_CodEmpresa != null ?
                new ObjectParameter("U_CodEmpresa", u_CodEmpresa) :
                new ObjectParameter("U_CodEmpresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_Usuario", u_CodUsuarioParameter, u_ContrasenaParameter, u_NombresParameter, u_ApellidosParameter, u_EmailParameter, u_SuperUsuarioParameter, u_WebParameter, u_APPParameter, u_UsuarioRegistroParameter, u_CodEmpresaParameter, rpta);
        }
    
        public virtual int POST_Usuario_Rol(string codUsuario, Nullable<int> roleId, ObjectParameter rpta)
        {
            var codUsuarioParameter = codUsuario != null ?
                new ObjectParameter("CodUsuario", codUsuario) :
                new ObjectParameter("CodUsuario", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POST_Usuario_Rol", codUsuarioParameter, roleIdParameter, rpta);
        }
    
        public virtual ObjectResult<USP_Web_Listar_Ayudantes_Result> GET_Listar_Ayudantes(Nullable<int> code, string busqGral, string codEmpresa)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(int));
    
            var busqGralParameter = busqGral != null ?
                new ObjectParameter("busqGral", busqGral) :
                new ObjectParameter("busqGral", typeof(string));
    
            var codEmpresaParameter = codEmpresa != null ?
                new ObjectParameter("CodEmpresa", codEmpresa) :
                new ObjectParameter("CodEmpresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_Ayudantes_Result>("GET_Listar_Ayudantes", codeParameter, busqGralParameter, codEmpresaParameter);
        }
    
        public virtual ObjectResult<USP_Web_Listar_Conductores_Result> GET_Listar_Conductores(Nullable<int> code, string busqGral, string codEmpresa)
        {
            var codeParameter = code.HasValue ?
                new ObjectParameter("Code", code) :
                new ObjectParameter("Code", typeof(int));
    
            var busqGralParameter = busqGral != null ?
                new ObjectParameter("busqGral", busqGral) :
                new ObjectParameter("busqGral", typeof(string));
    
            var codEmpresaParameter = codEmpresa != null ?
                new ObjectParameter("CodEmpresa", codEmpresa) :
                new ObjectParameter("CodEmpresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_Conductores_Result>("GET_Listar_Conductores", codeParameter, busqGralParameter, codEmpresaParameter);
        }
    
        public virtual ObjectResult<USP_Web_Listar_Transportista_Result> GET_Listar_Transportista(Nullable<int> u_Cod, string busqGral, string codEmpresa)
        {
            var u_CodParameter = u_Cod.HasValue ?
                new ObjectParameter("U_Cod", u_Cod) :
                new ObjectParameter("U_Cod", typeof(int));
    
            var busqGralParameter = busqGral != null ?
                new ObjectParameter("busqGral", busqGral) :
                new ObjectParameter("busqGral", typeof(string));
    
            var codEmpresaParameter = codEmpresa != null ?
                new ObjectParameter("CodEmpresa", codEmpresa) :
                new ObjectParameter("CodEmpresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_Web_Listar_Transportista_Result>("GET_Listar_Transportista", u_CodParameter, busqGralParameter, codEmpresaParameter);
        }
    
        public virtual int UPDATE_Ayudante_Docs(Nullable<int> u_NroDocumento, Nullable<int> u_EstadoDocs, string u_ObsEstadoDocs, string u_UsuarioModificacion, ObjectParameter rpta)
        {
            var u_NroDocumentoParameter = u_NroDocumento.HasValue ?
                new ObjectParameter("U_NroDocumento", u_NroDocumento) :
                new ObjectParameter("U_NroDocumento", typeof(int));
    
            var u_EstadoDocsParameter = u_EstadoDocs.HasValue ?
                new ObjectParameter("U_EstadoDocs", u_EstadoDocs) :
                new ObjectParameter("U_EstadoDocs", typeof(int));
    
            var u_ObsEstadoDocsParameter = u_ObsEstadoDocs != null ?
                new ObjectParameter("U_ObsEstadoDocs", u_ObsEstadoDocs) :
                new ObjectParameter("U_ObsEstadoDocs", typeof(string));
    
            var u_UsuarioModificacionParameter = u_UsuarioModificacion != null ?
                new ObjectParameter("U_UsuarioModificacion", u_UsuarioModificacion) :
                new ObjectParameter("U_UsuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_Ayudante_Docs", u_NroDocumentoParameter, u_EstadoDocsParameter, u_ObsEstadoDocsParameter, u_UsuarioModificacionParameter, rpta);
        }
    
        public virtual int UPDATE_Conductor_Docs(Nullable<int> u_NroDocumento, Nullable<int> u_EstadoDocs, string u_ObsEstadoDocs, string u_UsuarioModificacion, ObjectParameter rpta)
        {
            var u_NroDocumentoParameter = u_NroDocumento.HasValue ?
                new ObjectParameter("U_NroDocumento", u_NroDocumento) :
                new ObjectParameter("U_NroDocumento", typeof(int));
    
            var u_EstadoDocsParameter = u_EstadoDocs.HasValue ?
                new ObjectParameter("U_EstadoDocs", u_EstadoDocs) :
                new ObjectParameter("U_EstadoDocs", typeof(int));
    
            var u_ObsEstadoDocsParameter = u_ObsEstadoDocs != null ?
                new ObjectParameter("U_ObsEstadoDocs", u_ObsEstadoDocs) :
                new ObjectParameter("U_ObsEstadoDocs", typeof(string));
    
            var u_UsuarioModificacionParameter = u_UsuarioModificacion != null ?
                new ObjectParameter("U_UsuarioModificacion", u_UsuarioModificacion) :
                new ObjectParameter("U_UsuarioModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_Conductor_Docs", u_NroDocumentoParameter, u_EstadoDocsParameter, u_ObsEstadoDocsParameter, u_UsuarioModificacionParameter, rpta);
        }
    }
}
